Repository nromanen/Ch-133.Ruby, pull requests merged in 2022-04, with the labels that each got.

#62 Feature/issue_60
  client/public/locales/en/translation.json
  client/public/locales/uk/translation.json
  client/src/pages/SignUp/SignUp.js
  server/app/controllers/users/registrations_controller.rb
  server/app/models/user.rb
  server/config/locales/devise.uk.yml
  server/config/locales/en.yml
  server/config/locales/uk.yml
  server/spec/models/user_spec.rb
Labels: task

#78 Feature/issue_77
  server/Gemfile
  server/app/models/user.rb
  server/config/locales/en.yml
  server/config/locales/uk.yml
Labels: bug fix

#69 Feature/issue 56
  client/public/index.html
  client/public/locales/en/translation.json
  client/public/locales/uk/translation.json
  client/src/auth.js
  client/src/components/cookie-refresh.js
  client/src/components/custom-routes/custom-routes.js
  client/src/components/header/header.jsx
  client/src/components/header/header.scss
  client/src/components/menuList.js
  client/src/components/toster/message.js
  client/src/context.js
  client/src/index.js
  client/src/interceptor.js
  client/src/pages/SingIn/SingIn.js
  server/db/seeds.rb
  server/spec/models/user_spec.rb
Labels: bug, frontend

#59 Feature/issue 26
  client/public/index.html
  client/public/locales/en/translation.json
  client/public/locales/uk/translation.json
  client/src/auth.js
  client/src/components/cookie-refresh.js
  client/src/components/custom-routes/custom-routes.js
  client/src/components/header/header.jsx
  client/src/components/header/header.scss
  client/src/components/menuList.js
  client/src/components/toster/message.js
  client/src/context.js
  client/src/index.js
  client/src/interceptor.js
  client/src/pages/SingIn/SingIn.js
  client/src/signed_in.js
  server/app/models/role.rb
  server/app/models/user.rb
  server/db/seeds.rb
  server/db/seeds/roles.rb
  server/db/seeds/users.rb
  server/spec/models/user_spec.rb
Labels: task, new frontend feature

#74 Feature/issue 67
  client/package.json
  client/src/components/custom-routes/custom-routes.js
  client/src/consts.js
  client/src/pages/Advertisement/ShowAdvertisement/Advert/Advert.js
  client/src/pages/Advertisement/ShowAdvertisement/Advert/Advert.scss
  client/src/pages/Advertisement/ShowAdvertisement/Comment/Comment.js
  client/src/pages/Advertisement/ShowAdvertisement/Comment/Comment.scss
  client/src/pages/Advertisement/ShowAdvertisement/Comment/CreateComment.js
  client/src/pages/Advertisement/ShowAdvertisement/Comment/CreateComment.scss
  client/src/pages/Advertisement/ShowAdvertisement/Like/Like.js
  client/src/pages/Advertisement/ShowAdvertisement/Like/Like.scss
  client/src/pages/Advertisement/ShowAdvertisement/Owner/Owner.js
  client/src/pages/Advertisement/ShowAdvertisement/Owner/Owner.scss
  client/src/pages/Advertisement/ShowAdvertisement/ShowAdvertisement.js
  client/src/pages/Advertisement/ShowAdvertisement/ShowAdvertisement.scss
  server/app/controllers/comments_controller.rb
  server/app/models/comment.rb
  server/app/policies/advert_policy.rb
  server/app/serializers/advert_serializer.rb
  server/app/serializers/adverts_serializer.rb
  server/app/serializers/comment_serializer.rb
Labels: new frontend feature, new backend feature

#79 Feature/issue 75
  client/package.json
  client/src/pages/Advertisement/ShowAdvertisement/Comment/Comment.js
  client/src/pages/Advertisement/ShowAdvertisement/ShowAdvertisement.js
Labels: new frontend feature

#82 Feature/issue_90
  server/db/seeds/users.rb
Labels: heroku, bug fix

#73 Feature/issue 80
  client/src/components/header/header.scss
  client/src/components/toster/toster.js
  client/src/consts.js
  client/src/pages/Advertisement/ShowAdvertisement/Like/Like.js
  server/app/controllers/adverts_controller.rb
  server/app/controllers/likes_controller.rb
  server/app/models/advert.rb
  server/config/locales/en.yml
  server/config/locales/ru.yml
  server/config/locales/uk.yml
  server/config/routes.rb
Labels: task, frontend, new backend feature

#72 Feature/issue 71
  client/package.json
  client/public/locales/en/translation.json
  client/public/locales/uk/translation.json
  client/src/assets/img/defaultAvatar.png
  client/src/components/form-input/form-input.scss
  client/src/components/toster/message.js
  client/src/pages/UserInfo/UserInfo.js
  client/src/pages/UserInfo/UserInfo.scss
  server/Gemfile.lock
  server/app/controllers/user_infos_controller.rb
  server/app/models/user_info.rb
  server/app/serializers/user_infos_serializer.rb
  server/config/locales/en.yml
  server/config/locales/ru.yml
  server/config/locales/uk.yml
  server/spec/controllers/user_info_controller_spec.rb
  server/spec/factories.rb
  server/spec/models/user_info_spec.rb
  server/spec/rails_helper.rb
  server/spec/support/controller_macros.rb
  server/spec/support/devise.rb
  server/spec/support/factory_bot.rb
Labels: task

#86 Feature/issue 83
  client/src/pages/Advertisement/ShowAdvertisement/Advert/Advert.js
  client/src/pages/Advertisement/ShowAdvertisement/Comment/Comment.js
  client/src/pages/Advertisement/ShowAdvertisement/Owner/Owner.js
  client/src/pages/Advertisement/ShowAdvertisement/ShowAdvertisement.js
  server/app/controllers/comments_controller.rb
  server/app/models/advert.rb
  server/app/models/comment.rb
  server/app/models/user.rb
  server/config/locales/en.yml
Labels: frontend, new backend feature, bug fix

#85 Feature/issue 85
  client/public/index.html
  client/public/locales/en/translation.json
  client/public/locales/uk/translation.json
  client/src/auth.js
  client/src/components/cookie-refresh.js
  client/src/components/custom-routes/custom-routes.js
  client/src/components/header/header.jsx
  client/src/components/header/header.scss
  client/src/components/menuList.js
  client/src/components/toster/toster.js
  client/src/pages/Admin/ChangeRole/ChangeRole.js
  client/src/pages/Admin/ChangeRole/changeButton.js
  client/src/pages/Home/components/cards/cards.js
  client/src/signed_in.js
  server/app/controllers/roles_controller.rb
  server/app/controllers/users_controller.rb
  server/app/models/user.rb
  server/app/policies/user_policy.rb
  server/app/serializers/user_serializer.rb
  server/config/locales/en.yml
  server/config/locales/uk.yml
  server/config/routes.rb
Labels: task, new frontend feature, new backend feature

#96 ignore some tests
  .github/workflows/autho_delpoy.yml
  server/spec/controllers/user_info_controller_spec.rb
  server/spec/models/user_info_spec.rb
Labels: bug fix

#90 Feature/issue 88
  client/src/pages/Advertisement/ShowAdvertisement/Advert/Advert.scss
  client/src/pages/Advertisement/ShowAdvertisement/Comment/Comment.js
  client/src/pages/Advertisement/ShowAdvertisement/Comment/Comment.scss
  client/src/pages/Advertisement/ShowAdvertisement/Comment/CreateComment.js
  client/src/pages/Advertisement/ShowAdvertisement/Comment/CreateComment.scss
  client/src/pages/Advertisement/ShowAdvertisement/Like/Like.scss
  client/src/pages/Advertisement/ShowAdvertisement/ShowAdvertisement.js
  client/src/pages/Advertisement/ShowAdvertisement/ShowAdvertisement.scss
  server/app/controllers/comments_controller.rb
  server/app/models/advert.rb
  server/app/models/comment.rb
Labels: task

#102 add test
  server/app/controllers/user_infos_controller.rb
  server/config/environments/test.rb
  server/spec/controllers/user_info_controller_spec.rb
Labels: task

#105 little fixes
  client/.npmrc
  client/package.json
  client/src/components/custom-routes/custom-routes.js
  client/src/components/menuList.js
  client/src/components/menuList.scss
  client/src/pages/UserInfo/UserInfo.js
  client/src/pages/UserInfo/UserInfo.scss
  server/app/models/user_info.rb
  server/app/serializers/advert_serializer.rb
  server/config/locales/en.yml
  server/config/locales/uk.yml
Labels: bug fix

#107 Update translation
  client/public/locales/en/translation.json
  client/public/locales/uk/translation.json
  client/src/pages/UserInfo/UserInfo.js
  server/app/models/user.rb
  server/config/locales/en.yml
  server/config/locales/uk.yml
  server/spec/factories.rb
Labels: bug fix
