Repository nromanen/Ch-133.Ruby, pull requests merged in 2022-03, with the labels that each got.

#44 Feature/issue 33
  server/app/controllers/users/confirmations_controller.rb
  server/app/controllers/users/registrations_controller.rb
  server/app/controllers/users/unlocks_controller.rb
  server/app/models/user.rb
  server/config/environments/development.rb
  server/config/initializers/devise.rb
  server/config/routes.rb
Labels: task

#24 Feature/issue 20
  client/jsconfig.json
  client/package.json
  client/public/locales/en/translation.json
  client/public/locales/uk/translation.json
  client/src/components/custom-routes/custom-routes.js
  client/src/components/header/header.jsx
  client/src/components/header/header.scss
  client/src/components/switch-language/switch-language.js
  client/src/components/switch-language/switch-language.scss
  client/src/consts.js
  client/src/i18n.js
  client/src/index.js
  client/src/pages/Layout.js
  client/src/pages/SingIn/SingIn.js
Labels: task

#31 Feature/issue 25
  client/src/components/cookie-refresh.js
  client/src/components/custom-routes/custom-routes.js
  client/src/index.js
  client/src/pages/SingIn/SingIn.js
Labels: task

#39 Feature/issue 32
  client/README.md
  client/package.json
  client/public/index.html
  client/src/components/header/header.jsx
  client/src/components/header/header.scss
  client/src/components/menuList.js
  client/src/components/switch-language/switch-language.js
  client/src/context.js
  client/src/index.js
  client/src/pages/SingIn/SingIn.js
  server/app/models/user.rb
Labels: frontend

#45 Feature/issue 43
  client/package.json
  client/public/index.html
  client/public/locales/en/translation.json
  client/public/locales/uk/translation.json
  client/src/components/custom-routes/custom-routes.js
  client/src/components/footer/footer.js
  client/src/components/header/header.jsx
  client/src/components/header/header.scss
  client/src/components/menuList.js
  client/src/components/switch-language/switch-language.js
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.js
  client/src/pages/Home/components/cards/cards.js
  client/src/pages/Home/components/courosel/courosel.js
  client/src/pages/SignUp/SignUp.js
Labels: frontend

#46 Issue 34/categories front
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/components/custom-button/custom-button.scss
  client/src/components/custom-routes/custom-routes.js
  client/src/components/form-input/form-input.jsx
  client/src/consts.js
  client/src/index.js
  client/src/pages/Category/Categories.js
  client/src/pages/Category/Categories.scss
  client/src/pages/Category/CategoryNew.js
  client/src/pages/Category/CategoryPage.scss
  client/src/pages/Layout.js
  client/src/pages/NoPage/NoPage.js
  server/Gemfile
  server/Gemfile.lock
  server/app/controllers/categories_controller.rb
  server/app/controllers/comments_controller.rb
  server/app/models/advert.rb
  server/app/models/category.rb
  server/app/models/comment.rb
  server/app/models/user.rb
  server/config/locales/en.yml
  server/config/locales/ru.yml
  server/config/locales/uk.yml
  server/config/routes.rb
  server/db/schema.rb
Labels: frontend

#47 Feature/issue 44
  client/public/locales/en/translation.json
  client/public/locales/uk/translation.json
  client/src/components/custom-button/custom-button.scss
  client/src/components/custom-routes/custom-routes.js
  client/src/components/header/header.jsx
  client/src/components/header/header.scss
  client/src/components/menuList.js
  client/src/pages/NoPage/NoPage.js
  client/src/pages/NoPage/NoPage.scss
  client/src/pages/SignUp/SignUp.js
  server/app/models/user.rb
  server/db/seeds.rb
Labels: bug

#49 Feature/issue 45
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/components/cookie-refresh.js
  client/src/components/header/header.scss
  client/src/components/menuList.js
  client/src/pages/Home/Home.css
  client/src/pages/Home/Home.js
  client/src/pages/NoPage/NoPage.js
  client/src/pages/SignUp/SignUp.js
  client/src/pages/SingIn/SingIn.js
Labels: bug

#52 Feature/issue 46
  .idea/.gitignore
  client/src/components/cookie-refresh.js
  client/src/components/menuList.js
  client/src/consts.js
  server/.env.local.example
  server/README.md
Labels: bug

#54 Feature/issue_48
  client/src/consts.js
  client/src/pages/SignUp/SignUp.js
  server/app/controllers/users/registrations_controller.rb
  server/app/models/user.rb
  server/config/locales/en.yml
  server/spec/spec_helper.rb
Labels: task

#53 Feature/issue 47
  client/jsconfig.json
  client/package.json
  client/src/components/header/header.jsx
  client/src/components/menuList.js
  client/src/components/switch-language/switch-language.js
  client/src/components/toster/message.js
  client/src/components/toster/toster.js
  client/src/index.js
  client/src/interceptor.js
  client/src/pages/Home/components/cards/cards.js
  client/src/pages/Layout.js
  client/src/pages/SignUp/SignUp.js
  client/src/pages/SingIn/SingIn.js
  server/.env.local.example
  server/app/controllers/users/sessions_controller.rb
  server/config/locales/en.yml
  server/config/locales/ru.yml
  server/config/locales/uk.yml
  server/db/seeds.rb
Labels: new frontend feature

#58 feature/issue_57
  client/src/pages/UserInfo/UserInfo.js
  server/app/controllers/user_infos_controller.rb
Labels: task
